import initScrollSmooth from "./modules/scroll-suave.js";
import initAnimationScroll from "./modules/animationScroll.js";
import initAccordion from "./modules/accordion.js";
import initTabNav from "./modules/tabnav.js";
import { initModal, exitModal } from "./modules/modal.js";
import initToolTip from "./modules/tooltip.js";
import initDropDownMenu from "./modules/drodown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initAnimaNumeros from "./modules/anima-numeros.js";

initScrollSmooth();
initAnimationScroll();
initAccordion();
initTabNav();
initModal();
exitModal();
initToolTip();
initDropDownMenu();
initMenuMobile();
initAnimaNumeros();
